zone_name                 = "paramjyot2ray.com"
container_name            = "gatus"
availability_zones        = ["ca-central-1a", "ca-central-1b"]
az_count                  = 2
cluster_name              = "gatus-cluster"
cpu                       = 256
memory                    = 512
desired_count             = 2
domain_name               = "paramjyot2ray.com"
name                      = "vpc-gatus"
private_subnet_cidrs      = ["10.0.101.0/24", "10.0.102.0/24"]
public_subnet_cidrs       = ["10.0.1.0/24", "10.0.2.0/24"]
subdomain                 = "tm"
task_name                 = "gatus-task"
vpc_cidr                  = "10.0.0.0/16"
task_family               = "gatus-task"
manage_validation_records = false
