ui:
  title: "Gatus - Service Health"
  header: "ECS Fargate Health Dashboard"
  theme: "dark"

web:
  address: "0.0.0.0"
  port: 8080

storage:
  type: memory
  maximum-number-of-results: 200

endpoints:
  - name: google
    group: external
    url: https://www.google.com
    interval: 30s
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 500"

  - name: gatus-self
    group: internal
    url: http://localhost:8080/health
    interval: 30s
    conditions:
      - "[STATUS] == 200"

  - name: tm-homepage
    group: app
    url: https://tm.paramjyot2ray.com/
    interval: 30s
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 800"

